import { privateHeaders } from './payment-core';
export const escapeHtml = (value: string) => value.replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[char]!);
export function paymentPage(title: string, body: string, options: { status?: number; headers?: Record<string, string> } = {}) {
  return new Response(`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escapeHtml(title)} | Ganesha</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Figtree:wght@400;500;600;700;800&display=swap" rel="stylesheet"><style>
    *{box-sizing:border-box}body{margin:0;background:#FBFAF8;color:#17151F;font-family:Figtree,system-ui,sans-serif;line-height:1.6}a{color:#6C3BEE}header{max-width:1080px;margin:auto;padding:28px 24px}header a{text-decoration:none;color:#17151F;font-size:30px;font-weight:800;letter-spacing:-1.5px}header span{color:#6C3BEE}main{max-width:600px;margin:40px auto 80px;padding:40px;background:#FDFDFC;border:1px solid #E8E4ED;border-radius:24px;box-shadow:0 12px 40px #17151F06}.eyebrow{font-size:12px;text-transform:uppercase;letter-spacing:1.5px;font-weight:700;color:#6C3BEE}h1{font-size:38px;line-height:1.15;letter-spacing:-1.3px;margin:20px 0}p{color:#686371}.price{font-size:48px;font-weight:700;letter-spacing:-2px;color:#17151F;margin-bottom:0}.price small{font-size:16px;letter-spacing:0;font-weight:500}.notice{padding:16px 20px;background:#F5F3FB;border-radius:14px;font-size:14px}button,.button{display:inline-block;border:0;border-radius:12px;background:#6C3BEE;color:white;padding:16px 23px;font:600 16px Figtree,system-ui;text-decoration:none;cursor:pointer;min-height:52px}form{margin:26px 0}button:disabled{background:#D8D1E7;color:#5E566F;cursor:not-allowed}:focus-visible{outline:3px solid #A68AEF;outline-offset:4px}.access-link{overflow-wrap:anywhere;font-size:14px}ul{padding-left:22px;color:#686371}footer{margin-top:30px;font-size:13px;color:#7B7584}@media(max-width:640px){main{margin:16px 16px 40px;padding:28px 22px}h1{font-size:32px}}
    </style></head><body><header><a href="/">ganesha<span>.</span></a></header><main><div class="eyebrow">Your next possibility</div><h1>${escapeHtml(title)}</h1>${body}<footer>Ganesha · Test mode · No real charges</footer></main></body></html>`, {
      status: options.status || 200, headers: { ...privateHeaders(), 'Content-Type': 'text/html; charset=utf-8', 'Content-Language': 'en',
        'Content-Security-Policy': "default-src 'none'; style-src 'unsafe-inline' https://fonts.googleapis.com; font-src https://fonts.gstatic.com; form-action 'self' https://checkout.stripe.com; base-uri 'none'; frame-ancestors 'none'", ...options.headers },
    });
}
