/* Reference prototype v2: reads the canonical course and locale files. */
(async()=>{
'use strict';
const UI=window.GANESHA_LOCALES;
const shortLabels={
'pt-BR':['Aulas','Voltar','Ajuda','Etapa','Registrar prática','Revise sua prática','Conferir resposta','Sobre esta prévia','Fechar'],
en:['Lessons','Back','Help','Step','Record practice','Review your practice','Check answer','About this preview','Close'],
es:['Lecciones','Volver','Ayuda','Paso','Registrar práctica','Revisa tu práctica','Comprobar respuesta','Sobre esta vista previa','Cerrar'],
fr:['Leçons','Retour','Aide','Étape','Enregistrer la pratique','Vérifiez votre pratique','Vérifier la réponse','À propos de cet aperçu','Fermer'],
de:['Lektionen','Zurück','Hilfe','Schritt','Übung erfassen','Prüfe deine Übung','Antwort prüfen','Über diese Vorschau','Schließen'],
ja:['レッスン','戻る','ヘルプ','ステップ','実践を記録','実践を見直す','回答を確認','このプレビューについて','閉じる'],
hi:['पाठ','वापस','सहायता','चरण','अभ्यास दर्ज करें','अभ्यास की समीक्षा करें','उत्तर जाँचें','इस पूर्वावलोकन के बारे में','बंद करें'],
id:['Pelajaran','Kembali','Bantuan','Tahap','Catat praktik','Tinjau praktik Anda','Periksa jawaban','Tentang pratinjau ini','Tutup'],
ar:['الدروس','رجوع','مساعدة','الخطوة','سجّل الممارسة','راجع ممارستك','تحقق من الإجابة','حول هذه المعاينة','إغلاق'],
ko:['수업','뒤로','도움말','단계','실습 기록','실습 검토','답 확인','미리보기 안내','닫기'],
'zh-CN':['课程','返回','帮助','步骤','记录练习','检查练习','检查答案','关于此预览','关闭']};
const startStage=['Começar etapa','Start step','Empezar paso','Commencer l’étape','Schritt beginnen','ステップを始める','चरण शुरू करें','Mulai tahap','ابدأ الخطوة','단계 시작','开始步骤']; Object.keys(shortLabels).forEach((k,i)=>shortLabels[k].push(startStage[i]));
const query=new URLSearchParams(location.search);
let locale=Object.hasOwn(UI,query.get('lang'))?query.get('lang'):'pt-BR', screen=query.get('screen')==='lesson'?'lesson':'home', selected=Math.max(0,Math.min(6,Number(query.get('step'))||0));
let tool='claude',messages,course,lesson,steps,complete=[],drafts={},criteria={},answers={},feedbacks={},error='',savingFailed=false;
const $=s=>document.querySelector(s),esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ui=k=>UI[locale][k],label=i=>shortLabels[locale][i],num=n=>new Intl.NumberFormat(locale).format(n),m=k=>{const v=messages[k];if(!v)throw Error(`Missing canonical message ${locale}:${k}`);return typeof v==='string'?v:v.value;};
const art='assets/creative-workshop-transparent.png',logo='assets/native/icon-symbol-DQ7Exn6W.png',mascot='assets/native/ganesha-journey-wave-C0jV_k0n.png';
const paths={arrow:'M5 12h14m-6-6 6 6-6 6',back:'M19 12H5m6-6-6 6 6 6',check:'m5 12 4 4L19 6',pen:'m15 4 5 5-10 10-6 1 1-6z M13 6l5 5',page:'M5 3h10l4 4v14H5z M14 3v5h5 M8 12h8 M8 16h6',book:'M12 6C8 3 5 3 3 4v15c3-1 6-1 9 2 3-3 6-3 9-2V4c-2-1-5-1-9 2v15',globe:'M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0 M3 12h18 M12 3c5 5 5 13 0 18-5-5-5-13 0-18',info:'M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0 M12 11v6 M12 7v.1',flag:'M5 21V4 M5 4c5-3 9 3 14 0v10c-5 3-9-3-14 0',spark:'m12 3 2.5 6.5L21 12l-6.5 2.5L12 21l-2.5-6.5L3 12l6.5-2.5z'};
const icon=(k,size=18)=>`<svg aria-hidden="true" width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.65" stroke-linecap="round" stroke-linejoin="round"><path d="${paths[k]||paths.page}"/></svg>`, arrow=k=>`<span class="arrow">${icon(k||'arrow')}</span>`;
const has=i=>complete.includes(i),mark=i=>{if(!has(i))complete.push(i);save();};
function save(){try{localStorage.setItem('ganesha-native-design-v2',JSON.stringify({locale,selected,tool,complete,drafts,criteria,answers,feedbacks}));}catch{savingFailed=true;}}
function note(){return `<details class="context-note"><summary>${icon('info',13)}${ui('demoOnly')}</summary><p>${esc(ui('simulatedNote'))} ${esc(savingFailed?ui('storageError'):ui('saved'))} ${esc(ui('prototype'))}</p></details>`;}
function language(){return `<select data-locale aria-label="${ui('language')}">${Object.entries(UI).map(([code,v])=>`<option value="${code}" lang="${code}" ${code===locale?'selected':''}>${v.name}</option>`).join('')}</select>`;}
function toolSelect(){return `<select data-tool aria-label="${ui('tool')}"><option value="claude" ${tool==='claude'?'selected':''}>Claude</option><option value="codex" ${tool==='codex'?'selected':''}>Codex</option></select>`;}
function home(){const s=steps[selected];return `<div class="native-home"><aside class="native-sidebar"><div class="native-brand"><img src="${logo}" alt="">Ganesha</div><p class="side-caption">${label(0)}</p><button class="lesson-nav" data-action="home"><span class="lesson-symbol">${icon('book',16)}</span><span><strong>${esc(m(lesson.titleKey))}</strong><small>${num(complete.length)} / ${num(steps.length)} ${ui('completed')}</small></span></button><div class="side-bottom"><div class="side-controls"><div class="select-row">${icon('globe',15)}${language()}</div><div class="select-row">${icon('spark',15)}${toolSelect()}</div></div>${note()}</div></aside><main id="main" class="native-board"><div class="board-header"><h1 tabindex="-1">${ui('stages')} <span>${esc(m(lesson.titleKey))}</span></h1><div class="rail-controls"><button class="icon-button" data-move="-1" aria-label="${label(1)}" ${selected===0?'disabled':''}>${arrow('back')}</button><button class="icon-button" data-move="1" aria-label="${ui('next')}" ${selected===steps.length-1?'disabled':''}>${arrow()}</button></div></div><div class="rail-viewport"><ol class="step-rail">${steps.map((step,i)=>`<li><button class="step-card ${i===selected?'active':''}" data-select="${i}" aria-label="${esc(m(step.titleKey))}" ${i===selected?'aria-current="step"':''}><span class="step-symbol">${has(i)?icon('check',17):i===selected?'':icon(step.isAssessment?'check':step.exercise?'pen':'page',15)}</span><strong>${esc(m(step.titleKey))}</strong><small>${ui('stageTypes')[i]}</small>${i===selected?`<span class="state-dot">${has(i)?ui('done'):ui('current')}</span>`:''}</button></li>`).join('')}</ol></div><section class="stage-preview ${selected===0?'merge-start':''}"><div class="preview-main"><div class="preview-copy"><h2>${esc(m(s.titleKey))}</h2><p>${esc(m(s.objectiveKey))}</p><p style="margin-top:10px">${esc(m(s.expectedResultKey))}</p></div><img class="preview-figure" src="${art}" alt="" width="300" height="300"></div><div class="preview-bottom"><button class="button primary" data-action="enter">${has(selected)?ui('review'):label(9)}${arrow()}</button></div></section></main></div>`;}
function visual(s){if(s.id.endsWith('request-check')||s.exercise&&s.executionMode!=='external-real-task'&&!s.id.endsWith('transfer'))return '';if(!s.visual)return'';return `<div class="method-visual" aria-hidden="true"><span class="visual-node">${icon('page',24)}</span>${arrow()}${s.id.endsWith('transfer')?'<div><bdi>Claude</bdi><br><bdi>Codex</bdi></div>':`<span class="visual-node">${icon(s.id.endsWith('evidence-check')?'info':'check',24)}</span>`}</div><p class="visual-caption">${esc(m(s.visual.altKey))}</p>`;}
function practice(s){const rubric=course.rubrics.find(r=>r.id===s.exercise.rubricId);return `<form id="practice"><p class="mode-notice">${s.executionMode==='external-real-task'?ui('openPractice'):ui('simulated')+' · '+ui('simulatedNote')}</p><label class="activity-label" for="draft">${esc(m(s.exercise.promptKey))}</label><textarea class="draft" id="draft" dir="auto">${esc(drafts[s.id]||'')}</textarea><fieldset class="review-list"><legend>${label(5)}</legend>${rubric.criteria.map((c,i)=>`<label class="criterion"><input type="checkbox" value="${i}" name="criterion" ${(criteria[s.id]||[]).includes(i)?'checked':''}><span>${esc(m(c.labelKey))}</span></label>`).join('')}</fieldset><button class="button secondary" type="submit">${label(4)}${icon('check')}</button>${has(selected)?`<div class="feedback good" role="status">${icon('check')}<p>${ui('done')} · ${ui('openPractice')}</p></div>`:''}</form>`;}
function check(s){const q=s.check;return `<form id="check"><fieldset class="check-group"><legend>${esc(m(q.questionKey))}</legend>${q.options.map(option=>`<label class="answer"><input type="radio" name="answer" value="${option.id}" ${answers[s.id]===option.id?'checked':''}><span>${esc(m(option.labelKey))}</span></label>`).join('')}</fieldset><button class="button secondary" type="submit">${label(6)}${icon('check')}</button>${Object.hasOwn(feedbacks,s.id)?`<div class="feedback ${feedbacks[s.id]?'good':'error'}" role="status">${icon(feedbacks[s.id]?'check':'info')}<p>${esc(m(q.options.find(o=>o.id===answers[s.id]).feedbackKey))} ${esc(m(feedbacks[s.id]?q.successFeedbackKey:q.retryFeedbackKey))}</p></div>`:''}</form>`;}
function focused(){const s=steps[selected];const toolBlocks=s.toolVariants[tool].blocks.map(b=>`<p>${esc(m(b.textKey))}</p>`).join('');return `<div class="focus-root"><header class="focusbar"><div class="focus-left"><button class="button ghost" data-action="home">${arrow('back')}${label(1)}</button><span>${esc(m(lesson.titleKey))}</span></div><div class="focus-progress"><span>${ui('stageTypes')[selected]}</span><div class="progress-dots" aria-hidden="true">${steps.map((_,i)=>`<i class="${i===selected?'current':has(i)?'complete':''}"></i>`).join('')}</div></div><div class="focus-actions">${language()}<button class="button ghost" data-action="steps" aria-label="${ui('stages')}">${icon('book',15)}${num(selected+1)} / ${num(steps.length)}</button></div></header><main id="main" class="lesson-sheet"><h1 tabindex="-1">${esc(m(s.titleKey))}</h1><div class="lesson-grid"><div class="lesson-copy"><p class="objective">${esc(m(s.objectiveKey))}</p>${s.blocks.map(b=>b.kind==='callout'?`<div class="lesson-callout">${esc(m(b.textKey))}</div>`:`<p>${esc(m(b.textKey))}</p>`).join('')}</div><aside class="${selected===0?'art-aside':'visual-aside'}">${selected===0?`<img class="lesson-art" src="${art}" alt="" width="230" height="230">`:visual(s)}</aside></div><details class="tool-instruction" ${s.executionMode==='external-real-task'?'open':''}><summary>${icon('spark',16)}${ui('tool')} ${toolSelect()}</summary>${toolBlocks}</details><section class="activity">${s.exercise?practice(s):s.check?`<p class="activity-instruction">${esc(m(s.actionKey))}</p>${check(s)}`:`<p class="activity-instruction">${esc(m(s.actionKey))}</p>`}${error?`<div class="feedback error" role="alert">${icon('info')}<p>${esc(error)}</p></div>`:''}</section><p class="expected">${esc(m(s.expectedResultKey))}</p><footer class="lesson-footer"><button class="button ghost" data-action="previous" ${selected===0?'disabled':''}>${arrow('back')}${label(1)}</button><button class="button primary" data-action="next" ${s.kind!=='explain'&&!has(selected)?'disabled':''}>${ui('next')}${arrow()}</button></footer><div class="sheet-bottom">${note()}<button class="help-button" data-action="help"><img src="${mascot}" alt="">${label(2)}</button></div></main></div>`;}
function summary(){return `<main id="main" class="focus-root"><div class="lesson-sheet"><div class="sheet-summary"><img src="${mascot}" alt=""><h1 tabindex="-1">${ui('completedDemo')}</h1><p>${ui('summaryBody')}</p><button class="button primary" data-action="home">${ui('back')}${arrow()}</button></div>${note()}</div></main>`;}
function render(focus=false){document.documentElement.lang=locale;document.documentElement.dir=locale==='ar'?'rtl':'ltr';document.title=`Ganesha · ${m(lesson.titleKey)}`;$('#app').innerHTML=`<a class="skip" href="#main">${ui('skip')}</a>${screen==='home'?home():screen==='complete'?summary():focused()}<dialog id="dialog"></dialog>`;bind();if(focus)$('h1')?.focus({preventScroll:true});}
function go(i,mode='lesson'){selected=i;screen=mode;error='';save();render(true);if(mode==='home')document.querySelector(`[data-select="${i}"]`)?.scrollIntoView({block:'nearest',inline:'nearest'});else window.scrollTo({top:0,behavior:'instant'});}
function modal(kind){const s=steps[selected];const d=$('#dialog');d.innerHTML=`<button class="close" aria-label="${label(8)}">×</button><h2>${kind==='steps'?ui('stages'):ui('help')}</h2>${kind==='steps'?`<ol class="modal-steps">${steps.map((step,i)=>`<li><button data-modal-step="${i}" class="${i===selected?'current':''}">${num(i+1)}. ${esc(m(step.titleKey))}</button></li>`).join('')}</ol>`:`${s.hintKeys.map(k=>`<p>${esc(m(k))}</p>`).join('')}<hr>${s.criteriaKeys.map(k=>`<p>${esc(m(k))}</p>`).join('')}`}`;d.querySelector('.close').addEventListener('click',()=>d.close());d.querySelectorAll('[data-modal-step]').forEach(b=>b.addEventListener('click',()=>{d.close();go(Number(b.dataset.modalStep));}));d.showModal();}
function bind(){document.querySelectorAll('[data-locale]').forEach(el=>el.addEventListener('change',async e=>{locale=e.target.value;await loadLocale();render();save();}));document.querySelectorAll('[data-tool]').forEach(el=>el.addEventListener('change',e=>{tool=e.target.value;save();render();}));document.querySelectorAll('[data-select]').forEach(b=>b.addEventListener('click',()=>go(Number(b.dataset.select),'home')));document.querySelectorAll('[data-move]').forEach(b=>b.addEventListener('click',()=>go(Math.max(0,Math.min(steps.length-1,selected+Number(b.dataset.move))),'home')));document.querySelectorAll('[data-action]').forEach(b=>b.addEventListener('click',()=>{const action=b.dataset.action;if(action==='home'){screen='home';render(true);return;}if(action==='enter'){go(selected);return;}if(action==='steps'||action==='help'){modal(action);return;}if(action==='previous'){go(Math.max(0,selected-1));return;}if(action==='next'){if(steps[selected].kind==='explain')mark(selected);if(selected===steps.length-1){if(steps.every((_,i)=>has(i))){screen='complete';render(true);}else{error=ui('gate');render();}}else go(selected+1);}}));const s=steps[selected];$('#draft')?.addEventListener('input',e=>{drafts[s.id]=e.target.value;complete=complete.filter(i=>i!==selected);criteria[s.id]=[];document.querySelectorAll('[name=criterion]').forEach(c=>c.checked=false);$('[data-action=next]').disabled=true;save();});document.querySelectorAll('[name=criterion]').forEach(c=>c.addEventListener('change',()=>{criteria[s.id]=[...document.querySelectorAll('[name=criterion]:checked')].map(c=>Number(c.value));complete=complete.filter(i=>i!==selected);$('[data-action=next]').disabled=true;save();}));$('#practice')?.addEventListener('submit',e=>{e.preventDefault();const rubric=course.rubrics.find(r=>r.id===s.exercise.rubricId);if(!(drafts[s.id]||'').trim()||(criteria[s.id]||[]).length!==rubric.criteria.length){error=ui('gate');render();return;}error='';mark(selected);render();});document.querySelectorAll('[name=answer]').forEach(r=>r.addEventListener('change',()=>{answers[s.id]=r.value;delete feedbacks[s.id];complete=complete.filter(i=>i!==selected);$('[data-action=next]').disabled=true;save();}));$('#check')?.addEventListener('submit',e=>{e.preventDefault();if(!answers[s.id]){error=ui('checkRequired');render();return;}error='';feedbacks[s.id]=s.check.correctOptionIds.includes(answers[s.id]);if(feedbacks[s.id])mark(selected);save();render();});}
async function loadLocale(){const response=await fetch(`content/locales/${locale}.json`);if(!response.ok)throw Error('locale unavailable');messages=(await response.json()).messages;}
try{course=await(await fetch('content/curriculum/course.json')).json();lesson=course.lessons.find(l=>course.releasedLessonIds.includes(l.id))||course.lessons.find(l=>l.id==='lesson.first-request');steps=lesson.steps;try{const v=JSON.parse(localStorage.getItem('ganesha-native-design-v2')||'null');if(v){tool=['claude','codex'].includes(v.tool)?v.tool:tool;complete=Array.isArray(v.complete)?v.complete:[];drafts=v.drafts||{};criteria=v.criteria||{};answers=v.answers||{};feedbacks=v.feedbacks||{};if(!query.has('step'))selected=Math.min(steps.length-1,v.selected||0);}}catch{savingFailed=true;}await loadLocale();render();}catch(error){$('#app').innerHTML=`<main class="focus-root"><section class="lesson-sheet"><h1>${ui('unavailableTitle')}</h1><p>${ui('unavailableBody')}</p><p>${ui('prototype')}</p></section></main>`;console.error(error);}
})();
