const course=window.ASTRA_COURSE, visuals=window.ASTRA_VISUALS;
const main=document.querySelector('#main');
const params=new URLSearchParams(location.search);
const escapeHTML=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const purposes=[
'Transforme anotações em um aviso útil e confira se a resposta respeitou os fatos.',
'Salve uma página de verdade e veja o mesmo arquivo aberto no navegador.',
'Ajude o visitante a encontrar as informações sem perder os fatos confirmados.',
'Compare o que deveria acontecer com o que você observa na página.',
'Veja uma entrada mudar a lista de tarefas e a contagem de pendências.',
'Distinga registros de mesmo nome e recuse valores que não atendem às regras.',
'Separe o programa dos dados e experimente recuperar uma cópia.',
'Descreva um problema, peça uma correção pequena e tente novamente.',
'Prepare lembretes usando uma regra que você consegue prever e conferir.',
'Repita a regra e confira se o histórico conserva uma preparação por tarefa.',
'Organize arquivos e instruções para uma pessoa que não acompanhou a construção.',
'Aplique o método a outro problema, com seus próprios dados, regra e testes.'
];
function inline(raw){return escapeHTML(raw).replace(/`([^`]+)`/g,'<code>$1</code>').replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>').replace(/<code>COMECE-AQUI\.md<\/code>/g,'<a href="?view=welcome">orientação inicial</a>').replace(/\[([^\]]+)\]\(([^)]+)\)/g,(m,t,h)=>`<a href="${h.startsWith('http')?h:'source/'+h}">${t}</a>`);}
function markdown(raw){
 const lines=raw.split('\n'),out=[];let i=0;
 while(i<lines.length){let s=lines[i];if(!s.trim()){i++;continue;}
  if(s.startsWith('```')){let code=[];i++;while(i<lines.length&&!lines[i].startsWith('```'))code.push(lines[i++]);i++;
   const val=code.join('\n');out.push(`<section class="prompt"><div class="prompt-top"><span>TEXTO PARA USAR NA ATIVIDADE</span><button type="button" class="copy-prompt">Copiar texto</button></div><pre><code>${escapeHTML(val)}</code></pre></section>`);continue;}
  if(/^#{1,3} /.test(s)){const level=s.match(/^#+/)[0].length;out.push(`<h${Math.min(3,level+1)}>${inline(s.replace(/^#+ /,''))}</h${Math.min(3,level+1)}>`);i++;continue;}
  if(s.startsWith('> ')){const rows=[];while(i<lines.length&&lines[i].startsWith('> '))rows.push(lines[i++].slice(2));out.push(`<blockquote>${inline(rows.join(' '))}</blockquote>`);continue;}
  if(s.startsWith('|')){const rows=[];while(i<lines.length&&lines[i].startsWith('|'))rows.push(lines[i++]);const cells=r=>r.replace(/^\||\|$/g,'').split('|').map(x=>x.trim());out.push(`<div class="table-wrap"><table><thead><tr>${cells(rows[0]).map(x=>`<th scope="col">${inline(x)}</th>`).join('')}</tr></thead><tbody>${rows.slice(2).map(r=>`<tr>${cells(r).map(x=>`<td>${inline(x)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`);continue;}
  if(/^(- |\d+\. )/.test(s)){const ordered=/^\d/.test(s),tag=ordered?'ol':'ul',items=[];while(i<lines.length&&/^(- |\d+\. )/.test(lines[i]))items.push(lines[i++].replace(/^(- |\d+\. )/,''));out.push(`<${tag}>${items.map(x=>`<li>${inline(x)}</li>`).join('')}</${tag}>`);continue;}
  const para=[];while(i<lines.length&&lines[i].trim()&&!/^(```|#{1,3} |\> |\|)/.test(lines[i]))para.push(lines[i++]);
  const text=para.join(' '),cls=/^\*\*(Exemplo preparado|Demonstração preparada)/.test(text)?'example-text':/^\*\*Ponto de parada/.test(text)?'checkpoint':'';
  out.push(`<p${cls?` class="${cls}"`:''}>${inline(text)}</p>`);
 }
 return out.join('\n');
}
function cards(v){return `<div class="visual-grid ${[2,4].includes(v.panels.length)?'two':''}">${v.panels.map((p,i)=>`<div class="visual-card"><div class="card-label"><span class="index-disc" aria-hidden="true">${i+1}</span>${escapeHTML(p.label)}</div>${p.items.map(x=>{if(typeof x==='string')x={text:x};return `<p class="item ${x.tone||''}">${escapeHTML(x.text)}</p>`;}).join('')}</div>`).join('')}</div>`;}
let taskStage=0,historyCount=0,restoreStage=0;
function tasks(){const states=[{n:0,t:[]},{n:2,t:[['Separar vasos',false],['Preparar mesa',false]]},{n:1,t:[['Separar vasos',true],['Preparar mesa',false]]},{n:0,t:[['Separar vasos',true]]}];const s=states[taskStage];return `<div class="task-demo"><div class="counter">${s.n} <span>${s.n===1?'pendência':'pendências'}</span></div>${s.t.length?s.t.map(t=>`<div class="task"><span class="state-dot ${t[1]?'done':''}" aria-hidden="true">${t[1]?'✓':''}</span><div>${t[0]}<small>${t[1]?'Concluída':'Pendente'}</small></div></div>`).join(''):'<p class="task-empty">Lista vazia</p>'}</div><div class="visual-actions"><button class="primary" id="task-next">${['Adicionar as duas tarefas do exemplo','Concluir Separar vasos','Excluir Preparar mesa','Recomeçar exemplo'][taskStage]}</button></div><p class="demo-note">Exemplo interativo com dados preparados. Não modifica o aplicativo do aluno.</p>`;}
function ruleRows(days=3){const rows=[['Separar vasos',0,false],['Preparar mesa',1,false],['Conferir cadeiras',days,false],['Imprimir roteiro',-1,true]];return `<div class="rule-table">${rows.map(([name,d,done])=>{const enters=!done&&d<=1;return `<div class="rule-row"><strong>${name}</strong><span>${d} ${Math.abs(d)===1?'dia':'dias'} · ${done?'concluída':'pendente'}</span><span class="rule-result ${enters?'':'no'}">${enters?'Entra: duas condições atendidas':done?'Fica fora: concluída':'Fica fora: prazo maior que 1'}</span></div>`;}).join('')}</div><p class="demo-status">${rows.filter(r=>!r[2]&&r[1]<=1).length} lembretes nesta prévia preparada. Nenhuma mensagem enviada.</p>`;}
function figure(v){
 let body=cards(v);
 if(v.kind==='fileflow')body=`<div class="visual-grid"><div class="visual-card"><div class="card-label"><span class="index-disc">1</span>Trecho no editor</div><div class="code-scene"><span>&lt;h1&gt;</span><br>Oficina Aurora<br><span>&lt;/h1&gt;</span></div><p class="item">Salvar como <code>site.html</code></p></div><div class="visual-card"><div class="card-label"><span class="index-disc">2</span>Arquivo na pasta</div><div class="file-symbol" aria-hidden="true">HTML</div><p class="item"><code>oficina-aurora/<br>└ site.html</code></p><p class="item bad">Confira se não virou <code>site.html.txt</code>.</p></div><div class="visual-card"><div class="card-label"><span class="index-disc">3</span>Página no navegador</div><div class="mini-page"><div class="mini-bar"></div><h3>Oficina Aurora</h3><p>Cuidados com plantas em vasos</p><p><strong>Sábado · 15h às 17h</strong></p><span class="mini-pill">Exemplo fictício</span></div></div></div>`;
 if(v.kind==='hierarchy')body=`<div class="visual-grid two"><div class="visual-card"><div class="card-label">Antes · informação misturada</div><div class="mini-page before-page"><p>Gratuito. Sala Girassol. Oficina Aurora. Materiais fornecidos. Sábado, 15h–17h. Cuidados com plantas em vasos. Data completa e endereço a confirmar.</p></div><p class="item">O horário se perde entre os outros fatos.</p></div><div class="visual-card"><div class="card-label">Depois · perguntas respondidas</div><div class="mini-page"><h3>Oficina Aurora</h3><p>Cuidados com plantas em vasos</p><p><strong>Quando e onde</strong><br>Sábado · 15h–17h<br>Sala Girassol</p><p><strong>O que está incluído</strong><br>Gratuito · materiais fornecidos</p><span class="mini-pill">Data e endereço a confirmar</span></div></div></div>`;
 if(v.kind==='package')body=`<div class="file-tree" aria-label="Arquivos da pasta de entrega">entrega-aurora/<br>├ LEIA-ME.txt <span>— comece pelas instruções</span><br>├ site.html <span>— informações da oficina</span><br>├ app.html <span>— tarefas e lembretes</span><br>└ dados-exemplo.json <span>— tarefas + histórico</span></div><div class="package-links"><div><code>site.html</code><p>Abrir organizador de treino</p></div><div class="both-ways" aria-label="Links de ida e volta">⇄</div><div><code>app.html</code><p>Voltar às informações da oficina</p></div></div>`;
 if(v.kind==='tasks')body=`<div id="task-stage">${tasks()}</div>`;
 if(v.kind==='rule')body=`<div id="rule-results" aria-live="polite">${ruleRows()}</div><div class="visual-actions"><label for="rule-days">Mude o prazo de Conferir cadeiras</label><select id="rule-days"><option value="3">3 dias</option><option value="2">2 dias</option><option value="1">1 dia</option><option value="-2">−2 dias</option></select></div><p class="demo-note">Só esse prazo muda. Compare o motivo de entrada ou saída.</p>`;
 if(v.kind==='identity')body+=`<div class="numberline" aria-label="Significado dos dias restantes"><div><b>−1</b>um dia de atraso</div><div><b>0</b>hoje</div><div><b>1</b>daqui a um dia</div></div><div class="visual-actions"><label for="validation-value">Experimente um valor de dias</label><select id="validation-value"><option value="">Vazio</option><option value="1.5">1.5</option><option value="366">366</option><option value="0">0</option><option value="-30">−30</option><option value="365">365</option></select><button id="validate-value">Verificar este valor</button></div><p class="demo-status" id="validation-result" role="status">Regra do exemplo: número inteiro entre −30 e 365, sem campo vazio.</p>`;
 if(v.kind==='history')body+=`<div class="visual-actions"><button id="history-cancel">Cancelar preparação</button><button class="primary" id="history-confirm">Confirmar os dois candidatos</button><button id="history-reset">Recomeçar</button></div><p class="demo-status" id="history-result" role="status">Histórico do exemplo: 0 registros. Há dois candidatos novos.</p>`;
 if(v.kind==='storage')body+=`<div class="visual-actions"><button id="restore-next">Ver a restauração, passo a passo</button></div><p class="demo-status" id="restore-result" role="status">Cópia preparada: 4 registros, 3 pendências. Nenhum arquivo será importado nesta demonstração.</p>`;
 if(v.kind==='fileflow')body+=`<div class="visual-actions"><span class="letter-label">Salvar → abrir no navegador → recarregar após alterar</span></div>`;
 return `<figure class="visual" data-visual="${v.id}"><div class="visual-tag">Demonstração preparada · aula ${String(v.lesson).padStart(2,'0')}</div><h2>${escapeHTML(v.title)}</h2><p class="visual-subtitle">${escapeHTML(v.subtitle)}</p>${body}<figcaption>${escapeHTML(v.caption)}</figcaption></figure>`;
}
function bind(){
 document.querySelectorAll('.copy-prompt').forEach(b=>b.addEventListener('click',async()=>{const content=b.closest('.prompt').querySelector('code').textContent;try{await navigator.clipboard.writeText(content);b.textContent='Copiado';document.querySelector('#status').textContent='Texto copiado. Cole na sua ferramenta; nada foi enviado.';}catch{b.textContent='Selecione e copie o texto';document.querySelector('#status').textContent='Não foi possível copiar automaticamente. Selecione o texto do pedido e copie.';}}));
 const select=document.querySelector('#step-select');if(select)select.addEventListener('change',e=>location.href=e.target.value);
 const task=document.querySelector('#task-next');if(task)task.addEventListener('click',()=>{taskStage=(taskStage+1)%4;document.querySelector('#task-stage').innerHTML=tasks();bindTask();});
 document.querySelector('#rule-days')?.addEventListener('change',e=>document.querySelector('#rule-results').innerHTML=ruleRows(Number(e.target.value)));
 document.querySelector('#validate-value')?.addEventListener('click',()=>{const val=document.querySelector('#validation-value').value,n=Number(val),good=val!==''&&Number.isInteger(n)&&n>=-30&&n<=365;const p=document.querySelector('#validation-result');p.className='demo-status'+(good?'':' error');p.textContent=good?`Aceito: ${n}. ${n===0?'Zero significa hoje.':n<0?'Um valor negativo indica atraso.':'É um prazo inteiro dentro do intervalo.'}`:val===''?'Não aceitar: falta informar o prazo. Vazio não é zero.':!Number.isInteger(n)?'Não aceitar: este exercício usa dias inteiros.':'Não aceitar: use um inteiro entre −30 e 365.';});
 document.querySelector('#history-confirm')?.addEventListener('click',()=>{const repeated=historyCount===2;historyCount=2;document.querySelector('#history-result').textContent=repeated?'Histórico continua com 2 registros. A01 + prazo-v1 e A02 + prazo-v1 já foram preparados.':'Histórico: 2 registros. A01 + prazo-v1 e A02 + prazo-v1. Preparados localmente, não enviados.';});
 document.querySelector('#history-cancel')?.addEventListener('click',()=>document.querySelector('#history-result').textContent=`Preparação cancelada. Histórico permanece com ${historyCount} registros.`);
 document.querySelector('#history-reset')?.addEventListener('click',()=>{historyCount=0;document.querySelector('#history-result').textContent='Histórico do exemplo: 0 registros. Há dois candidatos novos.';});
 document.querySelector('#restore-next')?.addEventListener('click',()=>{const states=['Excluir Conferir cadeiras: 3 registros na lista. A cópia continua com 4.','Cancelar a importação: a lista continua com 3 registros.','Confirmar a cópia válida: 4 registros restaurados, com os mesmos IDs e 3 pendências.','Recusar versão 99: os 4 registros continuam intactos.','Recomeço: cópia com 4 registros e 3 pendências.'];document.querySelector('#restore-result').textContent=states[restoreStage%states.length];restoreStage++;});
}
function bindTask(){document.querySelector('#task-next').addEventListener('click',()=>{taskStage=(taskStage+1)%4;document.querySelector('#task-stage').innerHTML=tasks();bindTask();});document.querySelector('#task-next').focus();document.querySelector('#status').textContent=['Lista vazia: zero pendências.','Duas tarefas: duas pendências.','Uma concluída: uma pendência.','Uma tarefa concluída: zero pendências.'][taskStage];}
function lessonView(id,step){const lesson=course.lessons[id-1];const selected=lesson.steps[step-1];const v=visuals.find(x=>x.lesson===id&&x.step===step);const body=markdown(selected.body);const split=body.indexOf('</p>')+4;const prev=step>1?`?lesson=${id}&step=${step-1}`:id>1?`?lesson=${id-1}&step=${course.lessons[id-2].steps.length}`:'?view=course';const next=step<lesson.steps.length?`?lesson=${id}&step=${step+1}`:id<12?`?lesson=${id+1}&step=1`:'?view=course';
 document.title=`Ganesha · ${lesson.title}`;
 main.innerHTML=`<section class="surface"><div class="lesson-top"><div class="crumb"><a href="?view=course">12 aulas</a> <span aria-hidden="true"> / </span> <strong>${escapeHTML(lesson.title)}</strong></div><label class="sr-only" for="step-select">Ir para uma etapa desta aula</label><select id="step-select">${lesson.steps.map(s=>`<option value="?lesson=${id}&step=${s.number}" ${s.number===step?'selected':''}>${s.number}. ${escapeHTML(s.title)}</option>`).join('')}</select></div><div class="step-layout"><article class="step-main"><div class="step-heading"><p class="eyebrow">Aula ${String(id).padStart(2,'0')} · etapa ${step} de ${lesson.steps.length}</p><h1>${escapeHTML(selected.title)}</h1><p class="purpose">${purposes[id-1]}</p></div>${step===1?`<div class="prep">${inline(lesson.intro)}</div>`:''}${v?figure(v):''}<div class="reading">${body}</div><div class="pager"><a class="button secondary" href="${prev}">← ${step===1?'Voltar':'Etapa anterior'}</a><a class="button primary" href="${next}">${step<lesson.steps.length?'Próxima etapa':id<12?'Ir para a próxima aula':'Voltar ao mapa'} <span aria-hidden="true">→</span></a></div><a class="source-link" href="${lesson.file}">Texto original desta aula · versão ${course.version}</a></article><aside class="steps-nav" aria-label="Etapas desta aula"><h2>Nesta aula</h2><ol>${lesson.steps.map(s=>`<li><a href="?lesson=${id}&step=${s.number}" ${s.number===step?'aria-current="step"':''}><span class="step-number" aria-hidden="true">${s.number}</span><span>${escapeHTML(s.title)}</span></a></li>`).join('')}</ol><p class="side-note">Você pode voltar e consultar. Navegar pela prévia não registra execução nem avalia sua aprendizagem.</p><p class="side-note"><a href="?view=welcome">Como usar esta oficina</a></p></aside></div></section>`;bind();
}
function courseView(){document.title='Ganesha · Oficina Aurora';main.innerHTML=`<section class="surface"><div class="course-hero"><div><p class="eyebrow">Oficina de criação com IA</p><h1>Da primeira conversa a um projeto seu.</h1><p class="purpose">Aprenda a pedir, construir e conferir. Um exemplo acompanha você: a Oficina Aurora, um encontro fictício sobre plantas em vasos.</p><a class="button primary" href="?view=welcome">Começar pela orientação →</a></div><div class="course-object" aria-label="O que você vai construir"><div class="object-row"><div class="object-icon" aria-hidden="true">≡</div><div><strong>Uma página que informa</strong><span>Conteúdo claro e fatos conferidos</span></div></div><div class="object-row"><div class="object-icon" aria-hidden="true">✓</div><div><strong>Um aplicativo de tarefas</strong><span>Entradas, estados e dados recuperáveis</span></div></div><div class="object-row"><div class="object-icon" aria-hidden="true">↳</div><div><strong>Uma regra de lembretes</strong><span>Preparação local, sem envio de mensagens</span></div></div></div></div><div class="course-heading"><h2>Seu percurso, em 12 aulas</h2><p>61 etapas · no computador · no seu ritmo</p></div><div class="course-grid">${course.lessons.map(l=>`<a class="lesson-card" href="?lesson=${l.id}&step=1"><span class="eyebrow">Aula ${String(l.id).padStart(2,'0')}</span><h3>${escapeHTML(l.title)}</h3><p>${purposes[l.id-1]}</p><span class="meta">${l.steps.length} etapas · ${l.intro.match(/Reserve ([^*]+)\*/)?.[1]?.replace(/\.$/,'')||'tempo estimado'} →</span></a>`).join('')}</div></section>`;}
function welcomeView(){main.innerHTML=`<section class="surface"><article class="welcome"><p class="eyebrow">Antes de começar</p><h1>Um lugar para experimentar, com calma.</h1><p class="purpose">Você vai trabalhar em uma pasta de treino e usar informações fictícias. Esta orientação explica onde cada ação acontece.</p><div class="reading">${markdown(course.welcome.replace(/^# .+\n/,''))}</div><div class="pager"><a href="?view=course" class="button">Ver as aulas</a><a href="?lesson=1&step=1" class="button primary">Abrir a primeira aula →</a></div></article></section>`;bind();}
function galleryView(){main.innerHTML=`<section class="surface"><div class="gallery-intro"><p class="eyebrow">Entrega visual · revisão</p><h1>Treze gráficos para tornar o percurso visível.</h1><p class="purpose">Gráficos produzidos para as 12 aulas. Na etapa, o texto se adapta à tela; os SVGs abaixo são versões exportáveis com texto editável.</p></div><div class="gallery-grid">${visuals.map(v=>`<article class="gallery-card"><a href="assets/${v.id}.svg" aria-label="Abrir gráfico: ${escapeHTML(v.title)}"><img src="assets/${v.id}.svg" alt="${escapeHTML(v.alt)}" loading="lazy"></a><div class="gallery-info"><p class="eyebrow">Aula ${String(v.lesson).padStart(2,'0')} · etapa ${v.step}</p><h2>${escapeHTML(v.title)}</h2><p>${escapeHTML(v.subtitle)}</p><div class="links"><a href="?lesson=${v.lesson}&step=${v.step}">Ver na etapa →</a><a href="assets/${v.id}.svg" download>Baixar SVG</a></div></div></article>`).join('')}</div><section class="localization"><h2>Onze idiomas previstos. Uma versão escrita.</h2><p>Português brasileiro é a única versão nova. Os dez idiomas restantes precisam de tradução a partir desta autoria. Os textos dos gráficos estão separados no catálogo; código, IDs e nomes de arquivos ficam isolados da direção de leitura.</p><div class="locale-tags"><span class="ready">pt-BR · disponível</span>${['en','es','fr','de','ja','hi','id','ar','ko','zh-CN'].map(l=>`<span>${l} · pendente</span>`).join('')}</div><p>Os controles abaixo verificam apenas a composição. Não são traduções nem validação linguística.</p><div class="review-settings"><label><input type="checkbox" id="rtl-preview"> Espelhar layout (ensaio RTL)</label><label><input type="checkbox" id="expand-preview"> Ampliar texto do gráfico</label></div><div id="locale-sample">${figure(visuals.find(v=>v.kind==='identity'))}</div></section></section>`;bind();document.querySelector('#rtl-preview').addEventListener('change',e=>{document.querySelector('#locale-sample').dir=e.target.checked?'rtl':'ltr';});document.querySelector('#expand-preview').addEventListener('change',e=>document.documentElement.dataset.expand=e.target.checked?'yes':'no');}
const view=params.get('view');if(view==='course')courseView();else if(view==='welcome')welcomeView();else if(view==='gallery')galleryView();else{const id=Math.min(12,Math.max(1,Number(params.get('lesson'))||1));const step=Math.min(course.lessons[id-1].steps.length,Math.max(1,Number(params.get('step'))||1));lessonView(id,step);}
